class_name SpriteKit
extends RefCounted
## Runtime sprite loading with fallback. PNGs live in game/assets/sprites/
## (generated by tools/gen_sprites.py). Loaded via Image.load_from_file so no
## editor import pass is needed — works headless and windowed alike.
## If a sprite is missing we fall back to the old ColorRect placeholder, so the
## game never breaks on absent art.

static var _cache: Dictionary = {}

static func texture(sprite_name: String) -> Texture2D:
	if _cache.has(sprite_name):
		return _cache[sprite_name]
	var path := ProjectSettings.globalize_path("res://assets/sprites/").path_join(sprite_name + ".png")
	var tex: Texture2D = null
	if FileAccess.file_exists(path):
		var img := Image.load_from_file(path)
		if img != null:
			tex = ImageTexture.create_from_image(img)
	_cache[sprite_name] = tex
	return tex

## Centered sprite if the PNG exists, else a centered ColorRect of fallback size/color.
static func sprite(sprite_name: String, fallback_size: Vector2, fallback_color: Color) -> Node2D:
	var tex := texture(sprite_name)
	if tex != null:
		var s := Sprite2D.new()
		s.texture = tex
		s.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
		return s
	var r := ColorRect.new()
	r.size = fallback_size
	r.position = -fallback_size / 2.0
	r.color = fallback_color
	var holder := Node2D.new()
	holder.add_child(r)
	return holder
